hf_model_name: "EleutherAI/gpt-j"
model_name: "gpt_j"
prompt_name: "gpt-passive"
device: "cpu" 
subject_control: False
passive: True
names_file: "names_top_2.json"
action_file: "verbs.json"
nicknames_file: "nicknames.json"
