hf_model_name: "valhalla/t5-base-qa-qg-hl"
model_name: "t5" 
prompt_name: "t5-passive"
device: "cuda:0" 
subject_control: False
passive: True
names_file: "names_top_2.json"
action_file: "verbs.json"
nicknames_file: "nicknames.json"
out_dir: "short_instructions/results"
